/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sanz
 */
public class No1_Luas extends javax.swing.JFrame {

    /**
     * Creates new form No1_Luas
     */
    public No1_Luas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TinggiSegitiga = new javax.swing.JTextField();
        AlasSegitiga = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ButtonSegiitiga = new javax.swing.JButton();
        RLingkaran = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ButtonLingkaran = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        PanjangBalok = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        LebarBalok = new javax.swing.JTextField();
        TinggiBalok = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        ButtonBalok = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        PanjangPP = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        LebarPP = new javax.swing.JTextField();
        ButtonPP = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        HasilPP = new javax.swing.JLabel();
        HasilLingkaran = new javax.swing.JLabel();
        HasilBalok = new javax.swing.JLabel();
        HasilSegitiga = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Rekha", 0, 18)); // NOI18N
        jLabel1.setText("Luas Lingkaran");

        jLabel2.setFont(new java.awt.Font("Rasa SemiBold", 0, 24)); // NOI18N
        jLabel2.setText("Program Luas Bangun Datar & Ruang");

        jLabel3.setFont(new java.awt.Font("Rekha", 0, 18)); // NOI18N
        jLabel3.setText("Luas Segitiiga");

        jLabel4.setFont(new java.awt.Font("Rekha", 0, 18)); // NOI18N
        jLabel4.setText("Luas Persegi Panjang");

        jLabel5.setFont(new java.awt.Font("Rekha", 0, 18)); // NOI18N
        jLabel5.setText("Luas Balok");

        jLabel6.setText("Alas");

        jLabel7.setText("Tinggi");

        TinggiSegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TinggiSegitigaActionPerformed(evt);
            }
        });

        AlasSegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlasSegitigaActionPerformed(evt);
            }
        });

        jLabel8.setText("hasil");

        ButtonSegiitiga.setText("Hasil");
        ButtonSegiitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSegiitigaActionPerformed(evt);
            }
        });

        RLingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RLingkaranActionPerformed(evt);
            }
        });

        jLabel9.setText("Jari Jari = r");

        ButtonLingkaran.setText("Hasil");
        ButtonLingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLingkaranActionPerformed(evt);
            }
        });

        jLabel10.setText("hasil");

        jLabel11.setText("Panjang");

        PanjangBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanjangBalokActionPerformed(evt);
            }
        });

        jLabel12.setText("Lebar");

        LebarBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LebarBalokActionPerformed(evt);
            }
        });

        TinggiBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TinggiBalokActionPerformed(evt);
            }
        });

        jLabel13.setText("Tinggi");

        ButtonBalok.setText("Hasil");
        ButtonBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBalokActionPerformed(evt);
            }
        });

        jLabel14.setText("hasil");

        jLabel15.setText("Panjang");

        PanjangPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanjangPPActionPerformed(evt);
            }
        });

        jLabel16.setText("Lebar");

        LebarPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LebarPPActionPerformed(evt);
            }
        });

        ButtonPP.setText("Hasil");
        ButtonPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPPActionPerformed(evt);
            }
        });

        jLabel17.setText("hasil");

        HasilPP.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        HasilLingkaran.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        HasilBalok.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        HasilSegitiga.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(TinggiSegitiga, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AlasSegitiga, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RLingkaran, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(ButtonSegiitiga)
                                    .addGap(101, 101, 101))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(HasilSegitiga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(54, 54, 54)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(143, 143, 143)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(ButtonLingkaran)
                            .addComponent(HasilLingkaran, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TinggiBalok, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                        .addComponent(LebarBalok, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                        .addComponent(PanjangBalok, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel12)
                        .addComponent(jLabel14)
                        .addComponent(ButtonBalok))
                    .addComponent(HasilBalok, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(ButtonPP)
                    .addComponent(PanjangPP, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(HasilPP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LebarPP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)))
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(4, 4, 4)
                                .addComponent(AlasSegitiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(4, 4, 4)
                                .addComponent(RLingkaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addGap(8, 8, 8)
                        .addComponent(TinggiSegitiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(4, 4, 4)
                        .addComponent(PanjangBalok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addGap(8, 8, 8)
                        .addComponent(LebarBalok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(4, 4, 4)
                        .addComponent(PanjangPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addGap(8, 8, 8)
                        .addComponent(LebarPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ButtonSegiitiga)
                                    .addComponent(ButtonLingkaran))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ButtonPP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel17)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HasilPP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HasilLingkaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HasilSegitiga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TinggiBalok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonBalok)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HasilBalok, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TinggiSegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TinggiSegitigaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TinggiSegitigaActionPerformed

    private void AlasSegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlasSegitigaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlasSegitigaActionPerformed

    private void ButtonSegiitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSegiitigaActionPerformed
        // TODO add your handling code here:
        int a = Integer.parseInt(AlasSegitiga.getText());
        int t = Integer.parseInt(TinggiSegitiga.getText());
        double hasil =(a * t)/2;
        HasilSegitiga.setText(String.valueOf(hasil));
    }//GEN-LAST:event_ButtonSegiitigaActionPerformed

    private void RLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RLingkaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RLingkaranActionPerformed

    private void ButtonLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLingkaranActionPerformed
        // TODO add your handling code here:
        int r = Integer.parseInt(RLingkaran.getText());
        double hasil = 3.14 * r * r;
        HasilLingkaran.setText(String.valueOf(hasil));
    }//GEN-LAST:event_ButtonLingkaranActionPerformed

    private void PanjangBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanjangBalokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PanjangBalokActionPerformed

    private void LebarBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LebarBalokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LebarBalokActionPerformed

    private void TinggiBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TinggiBalokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TinggiBalokActionPerformed

    private void ButtonBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBalokActionPerformed
        // TODO add your handling code here:
        int p = Integer.parseInt(PanjangBalok.getText());
        int l = Integer.parseInt(LebarBalok.getText());
        int t = Integer.parseInt(TinggiBalok.getText());
        double hasil = 2 * ((p*l)+(p*t)+(l*t));
        HasilBalok.setText(String.valueOf(hasil));
    }//GEN-LAST:event_ButtonBalokActionPerformed

    private void PanjangPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanjangPPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PanjangPPActionPerformed

    private void LebarPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LebarPPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LebarPPActionPerformed

    private void ButtonPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPPActionPerformed
        // TODO add your handling code here:
        int p = Integer.parseInt(PanjangPP.getText());
        int l = Integer.parseInt(LebarPP.getText());
        double hasil = p * l;
        HasilPP.setText(String.valueOf(hasil));
    }//GEN-LAST:event_ButtonPPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(No1_Luas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(No1_Luas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(No1_Luas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(No1_Luas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new No1_Luas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AlasSegitiga;
    private javax.swing.JButton ButtonBalok;
    private javax.swing.JButton ButtonLingkaran;
    private javax.swing.JButton ButtonPP;
    private javax.swing.JButton ButtonSegiitiga;
    private javax.swing.JLabel HasilBalok;
    private javax.swing.JLabel HasilLingkaran;
    private javax.swing.JLabel HasilPP;
    private javax.swing.JLabel HasilSegitiga;
    private javax.swing.JTextField LebarBalok;
    private javax.swing.JTextField LebarPP;
    private javax.swing.JTextField PanjangBalok;
    private javax.swing.JTextField PanjangPP;
    private javax.swing.JTextField RLingkaran;
    private javax.swing.JTextField TinggiBalok;
    private javax.swing.JTextField TinggiSegitiga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
